ALTER TABLE software_installations
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE OR REPLACE FUNCTION safe_upsert_software_installation(
    p_device_id bigint,
    p_software_id integer,
    p_version text,
    p_observed_at timestamptz
)
RETURNS bigint
LANGUAGE sql
AS $function$
    INSERT INTO software_installations (
        device_id,
        software_id,
        installed_version,
        installed_at,
        last_seen_at
    ) VALUES (
        p_device_id,
        p_software_id,
        p_version,
        p_observed_at,
        p_observed_at
    )
    ON CONFLICT (device_id, software_id) DO UPDATE
    SET installed_version = EXCLUDED.installed_version,
        last_seen_at = GREATEST(software_installations.last_seen_at, EXCLUDED.last_seen_at),
        updated_at = clock_timestamp()
    WHERE EXCLUDED.last_seen_at >= software_installations.last_seen_at
    RETURNING id;
$function$;
